services:
  website:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - REDIS_URL=${REDIS_URL}
