version: "3.8"

services:
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api

  api:
    build: ./apps/api
    ports:
      - "8080:8080"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - REDIS_URL=${REDIS_URL}
